"""empty message

Revision ID: 340bbb503c19
Revises: 
Create Date: 2020-11-27 20:11:10.928380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340bbb503c19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.Text(), nullable=True),
    sa.Column('case_text', sa.Text(), nullable=True),
    sa.Column('embeddings', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('embeddings_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cases')
    # ### end Alembic commands ###
