"""empty message

Revision ID: 4c128366a072
Revises: 25d6b1be113a
Create Date: 2020-12-16 17:43:06.351358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c128366a072'
down_revision = '25d6b1be113a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('relations', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('cases', sa.Column('risk_factors', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('cases', sa.Column('similar_cases', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'similar_cases')
    op.drop_column('cases', 'risk_factors')
    op.drop_column('cases', 'relations')
    # ### end Alembic commands ###
