"""empty message

Revision ID: 8ffe5384fd93
Revises: e60781d4b781
Create Date: 2020-12-04 21:19:13.168959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffe5384fd93'
down_revision = 'e60781d4b781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('topic_verbs', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('cases', 'topic_word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('topic_word', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cases', 'topic_verbs')
    # ### end Alembic commands ###
