"""empty message

Revision ID: f1dd95b862f3
Revises: 3fe598482dd5
Create Date: 2020-12-12 20:02:38.463675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dd95b862f3'
down_revision = '3fe598482dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('relations', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'relations')
    # ### end Alembic commands ###
