"""empty message

Revision ID: f967e3f06171
Revises: 340bbb503c19
Create Date: 2020-12-03 14:26:57.059904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f967e3f06171'
down_revision = '340bbb503c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('close_date', sa.Date(), nullable=True))
    op.add_column('cases', sa.Column('country', sa.String(), nullable=True))
    op.add_column('cases', sa.Column('is_closed', sa.Boolean(), nullable=True))
    op.add_column('cases', sa.Column('open_date', sa.Date(), nullable=True))
    op.add_column('cases', sa.Column('service', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'service')
    op.drop_column('cases', 'open_date')
    op.drop_column('cases', 'is_closed')
    op.drop_column('cases', 'country')
    op.drop_column('cases', 'close_date')
    # ### end Alembic commands ###
