"""empty message

Revision ID: fc0389023bbf
Revises: 25d6b1be113a
Create Date: 2020-12-16 11:12:46.618103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0389023bbf'
down_revision = '25d6b1be113a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=True),
    sa.Column('open_date', sa.String(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('close_date', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('case_text', sa.Text(), nullable=True),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('relations', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('topic_verbs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('similar_cases', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cases')
    # ### end Alembic commands ###
